#encoding: utf-8
module CategoryProducts
  CATEGORY_PRODUCTS = {
      "Grid Computing" => ["TIBCO DataSynapse Federator™",
                           "TIBCO® Grid Analytics",
                           "TIBCO GridServer®" ],
      "Mobile Application Development" => [ "TIBCO Silver® BPM",
                                            "TIBCO Silver® BusinessWorks Service",
                                            "TIBCO Silver® CAP",
                                            "TIBCO Silver® Center"
      ],
      "TIBCO ActiveMatrix BusinessWorks" => [ "TIBCO ActiveMatrix BusinessWorks™ ActiveAspects Plug-in",
                                              "TIBCO ActiveMatrix BusinessWorks™ BPEL Extension",
                                              "TIBCO ActiveMatrix BusinessWorks™ Express",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for ActiveSpaces®",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for CICS",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for Data Conversion",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for EDI",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for Formvine®",
                                              "TIBCO ActiveMatrix BusinessWorks® Plug-in for HL7",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for MDM",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for Microsoft SharePoint",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for Mobile Integration",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for NetSuite",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for OpenSpirit®",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for Oracle E-Business Suite",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for OSB",
                                              "TIBCO® ActiveMatrix BusinessWorks™ Plug-in for Patterns - Search",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for REST and JSON",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for sFTP",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for TIBCO® Managed File Transfer",
                                              "TIBCO ActiveMatrix BusinessWorks ™ Plug-in for Twitter",
                                              "TIBCO ActiveMatrix BusinessWorks™ Plug-in for WebSphere MQ",
                                              "TIBCO ActiveMatrix BusinessWorks™ Service Engine",
                                              "TIBCO ActiveMatrix BusinessWorks™ Service Engine Plug-in for Oracle E-Business Suite",
                                              "TIBCO ActiveMatrix BusinessWorks™ Service Engine Plug-in for SmartMapper",
                                              "TIBCO ActiveMatrix BusinessWorks™ SmartMapper",
                                              "TIBCO ActiveMatrix BusinessWorks(TM) Plug-in for Facebook",
                                              "TIBCO BusinessWorks™ COBOL Copybook Plug-in",
                                              "TIBCO BusinessWorks™ EJB Plug-in",
                                              "TIBCO BusinessWorks™ IntegrationManager Plug-in",
                                              "TIBCO BusinessWorks™ Salesforce.com Plug-in"
      ],
      "TIBCO ActiveMatrix® Adapter Service Engine Software" => ["TIBCO ActiveMatrix® Adapter Service Engine for Files",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for IBM i",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for Kenan/BP",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for Lotus Notes",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for PeopleSoft",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for SAP",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for Siebel",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for Tuxedo",
                                                                "TIBCO ActiveMatrix® Adapter Service Engine for WebSphere MQ",
      ],
      "TIBCO ActiveMatrix® Adapter Software" => ["TIBCO ActiveMatrix® Adapter for Database",
                                                 "TIBCO ActiveMatrix® Adapter for Files",
                                                 "TIBCO ActiveMatrix® Adapter for IBM i",
                                                 "TIBCO ActiveMatrix® Adapter for Kenan/BP",
                                                 "TIBCO ActiveMatrix® Adapter for LDAP",
                                                 "TIBCO ActiveMatrix® Adapter for Lotus Notes",
                                                 "TIBCO ActiveMatrix® Adapter for PeopleSoft",
                                                 "TIBCO ActiveMatrix® Adapter for SAP",
                                                 "TIBCO ActiveMatrix® Adapter for Siebel",
                                                 "TIBCO ActiveMatrix® Adapter for Tuxedo",
                                                 "TIBCO ActiveMatrix® Adapter for WebSphere MQ"
      ],
      "SOA Development" => ["TIBCO ActiveMatrix® Binding Type for Adapters",
                            " TIBCO ActiveMatrix® Binding Type for EJB",
                            "TIBCO ActiveMatrix® Binding Type for LDAP",
                            "TIBCO ActiveMatrix® Binding Type for REST",
                            "TIBCO ActiveMatrix BusinessWorks™",
                            "TIBCO ActiveMatrix® Implementation Type for C++",
                            "TIBCO ActiveMatrix® Implementation Type for Microsoft CLR",
                            "TIBCO ActiveMatrix® Implementation Type for Scripting in Ruby",
                            "TIBCO ActiveMatrix® Implementation Type for TIBCO Adapters",
                            "TIBCO ActiveMatrix® Implementation Type for WCF Host",
                            "TIBCO ActiveMatrix® Management Agent for WCF",
                            "TIBCO ActiveMatrix® Management Agent for WebSphere",
                            "TIBCO ActiveMatrix® Registry",
                            "TIBCO ActiveMatrix® Runtime UDDI Server",
                            "TIBCO ActiveMatrix® Service Grid",
                            "TIBCO ActiveMatrix® Spotfire Enabler",
                            "TIBCO ActiveMatrix® Updater Tool for Java Runtime Environment (JRE)",
                            "TIBCO Configuration Tool",
                            "TIBCO® General Interface - Enterprise Edition",
                            "TIBCO PortalBuilder®",
                            "TIBCO PortalPack™ for BPM",
                            "TIBCO PortalPack™ for BusinessWorks",
                            "TIBCO PortalPack™ for InConcert",
                            "TIBCO PortalPack™ for Jive Forums",
                            "TIBCO PortalPack™ for SAP ITS"
      ],
      "SOA Governance" => ["TIBCO ActiveMatrix® Policy Director",
                           "TIBCO ActiveMatrix® Service Gateway"
      ],
      "BusinessConnect" => ["TIBCO BusinessConnect™",
                            "TIBCO BusinessConnect™ B2BPlugin for CMI",
                            "TIBCO BusinessConnect™ ConfigStore Management Interface Protocol",
                            "TIBCO BusinessConnect™ cXML Protocol",
                            "TIBCO BusinessConnect™ EBICS Protocol",
                            "TIBCO BusinessConnect™ ebXML Protocol",
                            "TIBCO BusinessConnect™ EDI Protocol HIPAA powered by Instream®",
                            "TIBCO BusinessConnect™ EDI Protocol powered by Instream®",
                            "TIBCO BusinessConnect™ Plug-in for FTP Server",
                            "TIBCO BusinessConnect Plug-in for SSH Server(TM)",
                            "TIBCO BusinessConnect™ Remote",
                            "TIBCO BusinessConnect™ RosettaNet Protocol",
                            "TIBCO BusinessConnect™ Services Plug-in",
                            " TIBCO BusinessConnect™ SOAP Protocol",
                            "TIBCO BusinessConnect™ Trading Community Management"
      ],
      "Foresight" => ["TIBCO Foresight™ Archive and Retrieval System",
                      "TIBCO Foresight™ - Common Documents",
                      "TIBCO Foresight™ EDISIM®",
                      "TIBCO Foresight™ HIPAA Validator® Desktop",
                      "TIBCO Foresight™ Instream®",
                      "TIBCO Foresight® Instream® MAC Adapter",
                      "TIBCO Foresight™ Studio",
                      "TIBCO Foresight™ Transaction Insight",
                      "TIBCO Foresight™ Translator"
      ],
      "TIBCO Adapter™ Software" => ["TIBCO ActiveMatrix® Adapter for JD Edwards EnterpriseOne",
                                    "TIBCO ActiveMatrix® Adapter for OSIsoft PI",
                                    "TIBCO Adapter™ for CICS",
                                    "TIBCO Adapter™ for ClarifyCRM",
                                    "TIBCO Adapter™ for COM",
                                    "TIBCO Adapter™ for CORBA",
                                    "TIBCO Adapter™ for EJB",
                                    "TIBCO Adapter™ for Files (IBM i)",
                                    "TIBCO ActiveMatrix® Adapter for Oracle BRM",
                                    "TIBCO Adapter™ for Files z/OS (MVS)",
                                    "TIBCO Adapter™ for Infranet",
                                    "TIBCO Adapter™ for Oracle Applications",
                                    "TIBCO Adapter™ for Remedy",
                                    "TIBCO Adapter™ for Siebel",
                                    "TIBCO Adapter™ for SWIFT",
                                    "TIBCO Adapter™ for Teradata",
                                    "TIBCO Adapter™ SDK"
      ],
      "Enterprise Service Bus (ESB)" => ["TIBCO ActiveMatrix® Service Bus"],
      "Mainframe Integration" => [ "TIBCO Mainframe Service Tracker™",
                                   "TIBCO Substation ES™"
      ],
      "Managed File Transfer (MFT)"=> ["TIBCO Slingshot™"],
      "Pattern Matching" => ["TIBCO® Patterns"],
      "TIBCO ActiveMatrix BusinessWorks™" => ["TIBCO BusinessWorks™ ProcessMonitor"],
      "Application Integration" => ["TIBCO Administrator™",
                                    "TIBCO BusinessFactor™",
                                    "TIBCO BusinessWorks™ Collaborator",
                                    "TIBCO® Database Drivers Supplement",
                                    "TIBCO Designer™",
                                    "TIBCO® EMS Client for IBM i",
                                    "TIBCO® EMS Client for z/OS (CICS)",
                                    "TIBCO® EMS Client for z/OS (MVS)",
                                    "TIBCO FormBuilder™",
                                    "TIBCO Harbor® High-speed File Transfer Client for UNIX",
                                    "TIBCO Harbor® High-speed File Transfer Client for Windows",
                                    "TIBCO Harbor® High-speed File Transfer Server for z/OS",
                                    "TIBCO InConcert®",
                                    "TIBCO IntegrationManager",
                                    "TIBCO® Mainframe RED",
                                    "TIBCO Mainframe WebUI™",
                                    "TIBCO® Managed File Transfer Command Center",
                                    "TIBCO® Managed File Transfer Internet Server",
                                    "TIBCO® Managed File Transfer Platform Server Agent",
                                    "TIBCO® Managed File Transfer Platform Server for IBM i",
                                    "TIBCO® Managed File Transfer Platform Server for UNIX",
                                    "TIBCO® Managed File Transfer Platform Server for Windows",
                                    "TIBCO® Managed File Transfer Platform Server for z/Linux",
                                    "TIBCO® Managed File Transfer Platform Server for z/OS",
                                    "TIBCO® MFT Internet Server/Command Center",
                                    "TIBCO® MFT Platform Server",
                                    " TIBCO® Object Service Broker",
                                    "TIBCO PartnerExpress™",
                                    "TIBCO RFID Interchange™",
                                    "TIBCO Runtime Agent™",
                                    "TIBCO Service Gateway™ for Files",
                                    "TIBCO XML Canon™"
      ],
      "TIBCO iProcess® Suite" => [
          "TIBCO iProcess® Analytics",
          "TIBCO iProcess® Analytics Export",
          "TIBCO iProcess® Client (ASP)",
          "TIBCO iProcess® Client (JSP)",
          "TIBCO iProcess® Conductor",
          "TIBCO iProcess® Decisions",
          "TIBCO iProcess® Engine",
          "TIBCO iProcess® Insight",
          "TIBCO iProcess® Modeler",
          "TIBCO iProcess® Objects",
          "TIBCO iProcess® Plug-ins",
          "TIBCO iProcess® Server Objects (Java)",
          "TIBCO iProcess® Server Objects (.NET)",
          "TIBCO iProcess® Technology Plug-ins",
          "TIBCO iProcess® Web Services Client Plug-in",
          "TIBCO iProcess® Web Services Schema",
          "TIBCO iProcess® Web Services Server Plug-in",
          "TIBCO iProcess® Workspace (Browser)",
          "TIBCO iProcess® Workspace Lite",
          "TIBCO iProcess® Workspace Plug-ins",
          "TIBCO iProcess® Workspace (Windows)"
      ],
      "Process and Workforce Automation" => ["TIBCO ActiveMatrix® BPM",
                                             " TIBCO ActiveMatrix® Decisions",
                                             "TIBCO Business Studio™ - BPM Edition",
                                             "TIBCO Business Studio™ for Analysts",
                                             "TIBCO Business Studio™ iProcess® Add-in",
                                             "TIBCO Business Studio™ - Process Edition",
                                             "TIBCO Designer™ Add-in for TIBCO Business Studio™"
      ],
      "Simple Apps, Forms, and Flows" => ["TIBCO Business Studio™ ActiveMatrix® Decisions Add-in",
                                          "TIBCO Formvine®",
                                          "TIBCO PageBus™"
      ],
      "In-Memory Data Grid" => ["TIBCO ActiveSpaces®"],
      "Transactional Application Server" => ["TIBCO ActiveSpaces® Transactions"],
      "MDM" => [ "TIBCO® MDM"],
      "Master Data Management" => [ "TIBCO Collaborative Information Manager™ Add-on for Global Data Synchronization",
                                    "TIBCO® Matching Engine/Platform",
                                    "TIBCO® MDM Studio"
      ],
      "Enterprise Messaging" => ["TIBCO Enterprise Message Service™",
                                 "TIBCO® Web Messaging for TIBCO Enterprise Message Service™"
      ],
      "High-Performance Messaging" => [
          "TIBCO FTL®",
          "TIBCO Rendezvous®"
      ],
      "Messaging" => [
          "TIBCO® EMS Transport Channel for WCF",
          "TIBCO Enterprise Message Service™ Central Administration",
          "TIBCO Enterprise Message Service™ OpenVMS C Client",
          "TIBCO Messaging Appliance™ P-7500",
          "TIBCO SmartPGM™",
          "TIBCO SmartSockets™",
          "TIBCO SmartSockets™ Cache"
      ],
      "Enterprise Monitoring" => [
          "TIBCO Hawk®",
          "TIBCO Hawk ActiveMatrix® Plug-in",
          "TIBCO Hawk® Adapter for Tivoli",
          "TIBCO Hawk® Database Adapter",
          "TIBCO Hawk® JMX Plug-in",
          "TIBCO Hawk® SNMP Adapter"
      ],
      "SLA & Business Metrics" => ["TIBCO ActiveMatrix® Service Performance Manager"],
      "TIBCO Infrastructure" => [ "TIBCO RTView™"],
      "Monitoring & Management" => [
          "TIBCO ActiveMatrix® Lifecycle Governance Registry Foundation",
          "TIBCO ActiveMatrix® Policy Manager",
          "TIBCO® RTView® BusinessWorks™ Monitor System",
          "TIBCO RTView - EMS Monitor System"
      ],
      "Complex Event Processing(CEP)" => [
          "TIBCO BusinessEvents®",
          "TIBCO BusinessEvents® Data Modeling",
          "TIBCO BusinessEvents® Decision Manager",
          "TIBCO BusinessEvents® Event Stream Processing",
          "TIBCO BusinessEvents® Extreme",
          "TIBCO BusinessEvents® Plug-in for EDI Healthcare Edition",
          "TIBCO BusinessEvents® Plug-in for EDI Standard Edition",
          "TIBCO BusinessEvents® Process Orchestration",
          "TIBCO BusinessEvents® Views",
          "TIBCO StreamBase CEP"
      ],
      "Log Management" => [
          "TIBCO® Iris",
          "TIBCO LogLogic® Log Management Intelligence",
          "TIBCO LogLogic® Security Event Management",
          "TIBCO LogLogic® Security Event Management 3.5.2"
      ],
      "Analytics & Visualization" =>["TIBCO® Enterprise Runtime for R",
                                     "TIBCO LogLogic® Artifact bundle",
                                     "TIBCO LogLogic® Compliance Manager",
                                     "TIBCO LogLogic® Compliance Suite - FISMA Edition",
                                     "TIBCO LogLogic® Compliance Suite - HIPAA Edition",
                                     "TIBCO LogLogic® Compliance Suite - ISO Edition",
                                     "TIBCO LogLogic® Compliance Suite - ITIL Edition",
                                     "TIBCO LogLogic® Compliance Suite - NERC Edition",
                                     "TIBCO LogLogic® Compliance Suite - PCI Edition",
                                     "TIBCO LogLogic® Compliance Suite - Sarbanes-Oxley Edition",
                                     "TIBCO LogLogic® Database Security Manager - Server",
                                     "TIBCO LogLogic® Database Security Manager Vulnerability Assessment",
                                     "TIBCO LogLogic® Enterprise Virtual Appliance",
                                     "TIBCO LogLogic® Management Center",
                                     "TIBCO LogLogic® Security Event Manager Enterprise Virtual Appliance",
                                     "TIBCO LogLogic® Security Event Manager Log Collector",
                                     "TIBCO LogLogic® Universal Collector (UC)",
                                     "TIBCO LogLogic® Universal Collector (UC) 2.2.0",
                                     "TIBCO Spotfire®",
                                     "TIBCO Spotfire® Advanced Data Services",
                                     "TIBCO Spotfire® Analytics Server",
                                     "TIBCO Spotfire® Automation Services",
                                     "TIBCO Spotfire® Clinical",
                                     "TIBCO Spotfire® Clinical Graphics",
                                     "TIBCO Spotfire® Connector for Composite Information Services",
                                     "TIBCO Spotfire® Connector for IBM Netezza",
                                     "TIBCO Spotfire® Connector for Oracle MySQL",
                                     "TIBCO Spotfire® Connector for Pipeline Pilot",
                                     "TIBCO Spotfire® Connector for Postgre SQL",
                                     "TIBCO Spotfire® Connector for SAP BW",
                                     "TIBCO Spotfire DecisionSite®",
                                     "TIBCO Spotfire® Deployment Kit",
                                     "TIBCO Spotfire® Deployment Kit for Apple iPad",
                                     "TIBCO Spotfire® Lead Discovery",
                                     "TIBCO Spotfire Miner™",
                                     "TIBCO Spotfire® Network Analytics",
                                     "TIBCO Spotfire® Operations Analytics",
                                     "TIBCO Spotfire® Qualification",
                                     "TIBCO Spotfire® S+",
                                     "TIBCO Spotfire® Server",
                                     "TIBCO Spotfire® Statistics Services",
                                     "TIBCO Spotfire® Web Player"
      ],
      "Social BPM" => [
          "TIBCO Nimbus™",
          "TIBCO Nimbus Control®",
          "TIBCO Nimbus Control® iPhone Edition",
          "TIBCO Nimbus Control® Player Desktop Edition",
          "TIBCO Nimbus Control® SM Connector"
      ],
      "Social Collaboration" => [ "tibbr®"]
  }

  UNCHANGED_PRODUCTS = [
      "TIBCO Silver® Fabric",
      "TIBCO Silver® Fabric Enabler for ActiveMatrix® BPM",
      "TIBCO Silver® Fabric Enabler for ActiveMatrix BusinessWorks™",
      "TIBCO Silver® Fabric Enabler for ActiveMatrix® Service Grid",
      "TIBCO Silver® Fabric Enabler for Adapter for Database",
      "TIBCO Silver® Fabric Enabler for Adapter for Files (Unix/Win)",
      "TIBCO Silver® Fabric Enabler for Adapter for LDAP",
      "TIBCO Silver® Fabric Enabler for Adapter for SAP",
      "TIBCO Silver® Fabric Enabler for BEA WebLogic",
      "TIBCO Silver® Fabric Enabler for IBM WebSphere",
      "TIBCO Silver® Fabric Enabler for RedHat JBoss 5.5.1",
      "TIBCO Silver® Fabric Enabler for RedHat JBoss 5.5.1",
      "TIBCO Silver® Fabric Enabler for TIBCO BusinessEvents®",
      "TIBCO Silver® Fabric Enabler for TIBCO Enterprise Message Service™",
      "TIBCO Silver® Mobile Core for Android",
      "TIBCO Silver Mobile ® Core For iOS",
      "TIBCO Silver® Mobile Server"
  ]



end